// AUTO-GENERATED by scripts/gen-lesson-meta.ts — do not edit by hand.
// Run `npm run gen-lesson-meta` after changing built-in lesson content.

export interface BuiltinStepMeta {
  id: string
  graded: boolean
  points: number
  minPoints: number
}

export interface BuiltinLessonMeta {
  version: number
  steps: BuiltinStepMeta[]
}

export const BUILTIN_LESSON_META: Record<string, BuiltinLessonMeta> = {
  "l1-talking-to-the-computer": {
    "version": 1,
    "steps": [
      {
        "id": "intro",
        "graded": false,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "print-a-string",
        "graded": true,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "first-program",
        "graded": true,
        "points": 100,
        "minPoints": 20
      }
    ]
  },
  "l2-boxes-that-remember": {
    "version": 2,
    "steps": [
      {
        "id": "intro",
        "graded": false,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "strings-and-types",
        "graded": false,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "store-and-print-text",
        "graded": true,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "last-value-wins",
        "graded": true,
        "points": 100,
        "minPoints": 20
      }
    ]
  },
  "l3-doing-the-math": {
    "version": 2,
    "steps": [
      {
        "id": "intro",
        "graded": false,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "fix-the-remainder",
        "graded": true,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "type-the-remainder",
        "graded": true,
        "points": 100,
        "minPoints": 20
      }
    ]
  },
  "l4-true-or-false": {
    "version": 2,
    "steps": [
      {
        "id": "meet-the-signs",
        "graded": false,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "intro",
        "graded": false,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "compare-numbers",
        "graded": true,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "exact-text",
        "graded": false,
        "points": 100,
        "minPoints": 20
      }
    ]
  },
  "l5-making-decisions": {
    "version": 3,
    "steps": [
      {
        "id": "one-fork",
        "graded": false,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "two-paths",
        "graded": false,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "fix-the-indent",
        "graded": true,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "first-door-wins",
        "graded": false,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "assemble",
        "graded": true,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "finish-it",
        "graded": true,
        "points": 100,
        "minPoints": 20
      }
    ]
  },
  "l6-over-and-over-again": {
    "version": 2,
    "steps": [
      {
        "id": "intro",
        "graded": false,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "for-loop-syntax",
        "graded": false,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "fix-the-loop-indent",
        "graded": true,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "fill-the-loop",
        "graded": true,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "fix-the-loop",
        "graded": true,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "count-with-n",
        "graded": false,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "print-hi-loop",
        "graded": true,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "count-1-to-n",
        "graded": true,
        "points": 100,
        "minPoints": 20
      }
    ]
  },
  "l7-loops-and-decisions": {
    "version": 2,
    "steps": [
      {
        "id": "intro",
        "graded": false,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "accumulate-in-a-loop",
        "graded": false,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "order-loop-and-if",
        "graded": true,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "accumulate-multiples-of-three",
        "graded": true,
        "points": 100,
        "minPoints": 20
      }
    ]
  },
  "l8-build-your-own-machine": {
    "version": 2,
    "steps": [
      {
        "id": "intro",
        "graded": false,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "define-a-function",
        "graded": false,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "pass-in",
        "graded": false,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "return-back",
        "graded": false,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "write-your-machine",
        "graded": true,
        "points": 100,
        "minPoints": 20
      }
    ]
  },
  "l9-fizzbuzzpop": {
    "version": 1,
    "steps": [
      {
        "id": "the-rules",
        "graded": false,
        "points": 100,
        "minPoints": 20
      },
      {
        "id": "capstone",
        "graded": true,
        "points": 100,
        "minPoints": 20
      }
    ]
  }
}
