// Generates functions/src/builtinLessonMeta.ts from the validated built-in lesson
// catalog. The Cloud Function that awards Sparks must know each lesson's
// authoritative step list (which steps exist, which are graded, and their point
// values) so it can compute rewards itself instead of trusting the client. The
// functions package can't import the React/Pyodide-laden app source directly, so
// we emit a small, dependency-free data module it can compile.
//
// Run `npm run gen-lesson-meta` after changing any built-in lesson content.

import { writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { rawLessons } from '../src/content/lessons/index'
import { lessonSchema } from '../src/content/schemas'
import { getMasteryChallenge } from '../src/content/mastery'

interface StepMeta {
  id: string
  graded: boolean
  points: number
  minPoints: number
}
interface MasteryMeta {
  recallCount: number
  maxQuestions: number
}
interface LessonMeta {
  version: number
  steps: StepMeta[]
  mastery?: MasteryMeta
}

// AI can ask up to 2 Apply questions; a forceStaticApply lesson is capped at its
// authored fallback count. maxQuestions is the cap on the server Spark award.
const MAX_AI_APPLY = 2

const meta: Record<string, LessonMeta> = {}
for (const [id, raw] of Object.entries(rawLessons)) {
  const lesson = lessonSchema.parse(raw)
  const entry: LessonMeta = {
    version: lesson.version,
    steps: lesson.steps.map((s) => ({
      id: s.id,
      graded: s.graded,
      points: s.points,
      minPoints: s.minPoints,
    })),
  }
  const spec = getMasteryChallenge(id)
  if (spec) {
    const maxApply = spec.forceStaticApply ? spec.applyFallback.length : MAX_AI_APPLY
    entry.mastery = {
      recallCount: spec.recall.length,
      maxQuestions: spec.recall.length + maxApply,
    }
  }
  meta[id] = entry
}

const banner = `// AUTO-GENERATED by scripts/gen-lesson-meta.ts — do not edit by hand.
// Run \`npm run gen-lesson-meta\` after changing built-in lesson content.

`

const types = `export interface BuiltinStepMeta {
  id: string
  graded: boolean
  points: number
  minPoints: number
}

export interface BuiltinMasteryMeta {
  /** Number of authored recall MCQs. */
  recallCount: number
  /** Cap on awarded mastery questions (recall + apply) — the anti-forge ceiling. */
  maxQuestions: number
}

export interface BuiltinLessonMeta {
  version: number
  steps: BuiltinStepMeta[]
  mastery?: BuiltinMasteryMeta
}

`

const body = `export const BUILTIN_LESSON_META: Record<string, BuiltinLessonMeta> = ${JSON.stringify(
  meta,
  null,
  2,
)}\n`

const here = path.dirname(fileURLToPath(import.meta.url))
const outPath = path.resolve(here, '../functions/src/builtinLessonMeta.ts')
writeFileSync(outPath, banner + types + body)

const lessonCount = Object.keys(meta).length
const stepCount = Object.values(meta).reduce((n, l) => n + l.steps.length, 0)
console.log(`Wrote ${lessonCount} lessons (${stepCount} steps) → ${outPath}`)
